#!/bin/bash
TZ=America/New_York # To modify container time zone

# add custom user in image
DOCKER_USER=anton
DOCKER_PASSWD=$(echo $DOCKER_USER | rev) # doesn't matter !!

# set this to change container name
CONTAINER_NAME=turbo-base
CONTAINER_TAG=latest

# optional
USE_GPU=true # this will require to install nvidia container toolkit

# prettify 
BLUE='\e[34m'
RED='\e[91m'
GREEN='\e[92m'
YELLOW='\e[93m'
NC='\e[0m'