#!/bin/bash
CONTAINER_NAME=dashing
RUNTIME_CONTAINER=$CONTAINER_NAME
BASE_IMAGE=nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
ROS2_DISTRO=dashing
TZ=America/New_York
DOCKER_USER=turbo
DOCKER_PASSWD=turbo
BUILD_AI_PACKAGE=true